version: '3.1'

services:

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306

  conqueso:
    build: .
    restart: always
    ports:
      - 8080:8080
